baseURL = "/"
languageCode = "en-us"
title = "We Ignite Tech"
theme = "kube"
description = "The We Ignite Tech website"
Paginate = 4

[Params]
  RSSLink = "/index.xml"
  author = "We Ignite Tech" # add your company name
  github = "https://github.com/WeIgniteTech/the-weignitetech-program" # add your github profile name
  twitter = "" # add your twitter profile
  email = "hello@weignite.tech"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
