baseURL = "https://weignitetech.github.io"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "We Ignite Tech"
theme = "meghna-hugo"
summaryLength = 10

[permalinks]
  pages = "/:section/:title/"

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"

# Menu
[menu]
    [[menu.nav]]
    name = "Program"
    URL = "about"
    weight = 2

    [[menu.nav]]
    name = "Vision"
    URL = "services"
    weight = 3

    [[menu.nav]]
    name = "Team"
    URL = "our-team"
    weight = 4

    [[menu.nav]]
    name = "Partners"
    URL = "portfolio"
    weight = 5

    #[[menu.nav]]
    #name = "Partnership"
    #URL = "pricing"
    #weight = 6

    #[[menu.nav]]
    #name = "Blog"
    #URL = "blog"
    #weight = 7

    [[menu.nav]]
    name = "Contact"
    URL = "contact-us"
    weight = 8

# Site params
[params]
home= "Home"
#logo = "images/logo.png"
logo = "images/wit4530.svg"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# Meta data
description = "The We Ignite Tech program"
author = "We Ignite Tech"
# Google Analitycs
googleAnalitycsID = "Your ID"
custom_css = ["css/custom.css"]


    # Main modal window for important messages
    [params.mainmodalwindow]
    enable = true

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/slider/hero-area.jpg"
    icon = "tf-ion-play"
    heading = "We Ignite Tech"
    content= "Providing IT talents and diversity to Norwegian businesses"
    btn = true
    btn1Text="Enroll in the program"
    btn1URL="#enroll"
    btn2Text="Hire a web developer"
    btn2URL="#contact-us"

    # call to action
    [params.cta]
    enable = true
    title = "Submissions are now closed"
    content = "The submissions to the program are now closed for the current session. But we are planning a new session in the begining of 2020. If you are interested, please contact us."
    btnURL = "#contact-us"
    btnText = "Contact us"

    # counter
    [params.counter]
    enable = true
    bgImage = "images/backgrounds/bg-1.jpg"
        [[params.counter.counterItem]]
        title = "Participants"
        icon = "tf-ion-android-happy"
        count = "12"

        [[params.counter.counterItem]]
        title = "Teaching hours"
        icon = "tf-ion-archive"
        count = "1260"

        [[params.counter.counterItem]]
        title = "Delivered projects"
        icon = "tf-ion-briefcase"
        count = "3"

        [[params.counter.counterItem]]
        title = "External speakers"
        icon = "tf-ion-document-text"
        count = "10"

    # footer
    [params.footer]
        copyright = "Themefisher Team"
        copyrightURL = "http://www.themefisher.com"

        # social Icons
         [[params.footer.socialIcon]]
         icon = "tf-ion-social-facebook"
         url = "https://www.facebook.com/We-Ignite-Tech-2434139386820603"

#        [[params.footer.socialIcon]]
#        icon = "tf-ion-social-twitter"
#        url = "#"

#        [[params.footer.socialIcon]]
#        icon = "tf-ion-social-google-outline"
#        url = "#"

#        [[params.footer.socialIcon]]
#        icon = "tf-ion-social-youtube"
#        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-instagram"
        url = "https://www.instagram.com/theweignitetechprogram/"

#        [[params.footer.socialIcon]]
#        icon = "tf-ion-social-dribbble-outline"
#        url = "#"

#        [[params.footer.socialIcon]]
#        icon = "tf-ion-social-pinterest-outline"
#        url = "#"
